{% set version = "1.4.5" %}

package:
  name: filterpy
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/f/filterpy/filterpy-{{ version }}.zip
  sha256: 4f2a4d39e4ea601b9ab42b2db08b5918a9538c168cff1c6895ae26646f3d73b1

build:
  noarch: python
  number: 2
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools

  run:
    - python >={{ python_min }}
    - numpy
    - matplotlib-base
    - scipy

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
  imports:
    - filterpy
    - filterpy.common
    - filterpy.discrete_bayes
    - filterpy.examples
    - filterpy.gh
    - filterpy.hinfinity
    - filterpy.kalman
    - filterpy.leastsq
    - filterpy.memory
    - filterpy.monte_carlo
    - filterpy.stats

about:
  home: https://github.com/rlabbe/filterpy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Kalman filters and other optimal and non-optimal estimation filters in Python'

  description: |
      Kalman filtering and optimal estimation library in Python.
      Kalman filter, Extended Kalman filter, Unscented Kalman filter,
      g-h, least squares, H Infinity, smoothers, and more.
      Has companion book 'Kalman and Bayesian Filters in Python'.
  doc_url: https://filterpy.readthedocs.io/en/latest/
  dev_url: https://github.com/rlabbe/filterpy

extra:
  recipe-maintainers:
    - hajapy
    - rlabbe
