{% set name = "filterpy" %}
{% set version = "1.2.3" %}
{% set sha256 = "208535c6aca1b4ca7b5409ad7c0becdda59dfb9c51883970e8201db31b6ea3e0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.zip
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - numpy
    - matplotlib
    - scipy

test:
  imports:
    - filterpy
    - filterpy.common
    - filterpy.discrete_bayes
    - filterpy.examples
    - filterpy.gh
    - filterpy.hinfinity
    - filterpy.kalman
    - filterpy.leastsq
    - filterpy.memory
    - filterpy.monte_carlo
    - filterpy.stats

about:
  home: https://github.com/rlabbe/filterpy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Kalman filters and other optimal and non-optimal estimation filters in Python'

  description: |
      Kalman filtering and optimal estimation library in Python.
      Kalman filter, Extended Kalman filter, Unscented Kalman filter,
      g-h, least squares, H Infinity, smoothers, and more.
      Has companion book 'Kalman and Bayesian Filters in Python'.
  doc_url: https://filterpy.readthedocs.io/en/latest/
  dev_url: https://github.com/rlabbe/filterpy

extra:
  recipe-maintainers:
    - hajapy
    - rlabbe
